[phases.setup]
nixPkgs = [
    "python311",
    "gcc",
    "zlib",
    "libxml2",
    "libxslt",
    "pango",
    "harfbuzz",
    "gdk-pixbuf",
    "cairo",
    "glib",
    "gobject-introspection"
]

[phases.build]
cmds = [
    "python manage.py migrate",
    "python manage.py collectstatic --noinput"
]

[start]
cmd = "gunicorn config.wsgi:application"